
export const sample_data : any []=[
  {
    id: '1',
    name: 'Spaghetti Carbonara',
    price: 12.99,
    tags: ['Italian', 'Pasta'],
    favorite: true,
    stars: '4.5',
    imageURL: './assets/food1.jpg',
    origins: ['Italy'],
    cookTime: '20 minutes',
  },
  {
    id: '2',
    name: 'Sushi Rolls',
    price: 18.49,
    tags: ['Japanese', 'Seafood'],
    favorite: false,
    stars: '4.8',
    imageURL: './assets/food2.jpg',
    origins: ['Japan'],
    cookTime: '30 minutes',
  },
  {
    id: '3',
    name: 'Cheeseburger',
    price: 9.99,
    tags: ['American', 'Fast Food'],
    favorite: true,
    stars: '4.2',
    imageURL: './assets/food3.jpg',
    origins: ['USA'],
    cookTime: '15 minutes',
  },
  {
    id: '4',
    name: 'Tacos',
    price: 8.75,
    tags: ['Mexican', 'Street Food'],
    favorite: true,
    stars: '4.7',
    imageURL: './assets/food4.jpg',
    origins: ['Mexico'],
    cookTime: '10 minutes',
  },
  {
    id: '5',
    name: 'Pad Thai',
    price: 13.25,
    tags: ['Thai', 'Noodles'],
    favorite: false,
    stars: '4.3',
    imageURL: './assets/food5.jpg',
    origins: ['Thailand'],
    cookTime: '25 minutes',
  }
]
export const sample_tags:any[]=[
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Spaghetti', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
]
